services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinematch-frontend
    ports:
      - "4200:80"
    networks:
      - cinematch-net
    depends_on:
      - gateway
      - core 

  gateway:
    image: node:22-alpine
    container_name: cinematch-gateway
    working_dir: /app
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: "3000"
      DATABASE_URL: "postgresql://cinematch_users_admin:cinematch_users_password@users_db:5432/cinemematch_users_db?schema=public"
      JWT_SECRET: "dev_secret_change_me"
      JWT_EXPIRES_IN: "1h"
    command: sh -c "npm ci && npm run dev"
    networks:
      - cinematch-net
    depends_on:
      users_db:
        condition: service_healthy


  core:
    build: ./core
    container_name: cinematch-core
    working_dir: /app
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    networks:
      - cinematch-net
    depends_on:
      movies_db:
        condition: service_healthy

  movies_db:
    image: postgres:15-alpine
    container_name: cinematch-movies-postgres
    restart: always
    environment:
      POSTGRES_USER: cinematch_movies_admin
      POSTGRES_PASSWORD: cinematch_movies_password
      POSTGRES_DB: cinematch_movies_db
      POSTGRES_HOST: movies_db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-movies-data:/var/lib/postgresql/data
    networks:
      - cinematch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinematch_movies_admin -d cinematch_movies_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  users_db:
    image: postgres:15-alpine
    container_name: cinematch-users-postgres
    restart: always
    environment:
      POSTGRES_USER: cinematch_users_admin
      POSTGRES_PASSWORD: cinematch_users_password
      POSTGRES_DB: cinematch_users_db
    ports:
      - "5433:5432"
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    networks:
      - cinematch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinematch_users_admin -d cinematch_users_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # S3 Compatible Object Storage
  s3-storage:
    image: minio/minio:latest
    container_name: cinematch-s3
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API Port (FastAPI and Frontend talk to this)
      - "9001:9001" # Web UI Port (For browser)
    command: server /data --console-address ":9001"
    volumes:
      - s3-data:/data
    networks:
      - cinematch-net

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinematch-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmq_admin
      RABBITMQ_DEFAULT_PASS: rmq_password
    ports:
      - "5672:5672"   # AMQP protocol port (FastAPI talks to this)
      - "15672:15672" # Web UI port (For browser)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - cinematch-net

networks:
  cinematch-net:
    driver: bridge

volumes:
  postgres-movies-data:
  users-postgres-data:
  s3-data:
  rabbitmq-data:
    
